[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "BWK7ZQWjQ9fweneHfsYmof7znPr5GyedCWs2J8JhHxD3"

[programs.devnet]
counter = "BWK7ZQWjQ9fweneHfsYmof7znPr5GyedCWs2J8JhHxD3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/wallet/left-solana-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
