[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "9WykwriEQGT1RjzJvAa7a31AQ8ZtHGnvmXRaeQ47oQLk"

[programs.devnet]
counter = "9WykwriEQGT1RjzJvAa7a31AQ8ZtHGnvmXRaeQ47oQLk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/wallet/test1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
