[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "F6PrVaeL2TegV2fmXFGW1dQeCXCCBZffn1JT5PUEiPMM"

[programs.devnet]
counter = "F6PrVaeL2TegV2fmXFGW1dQeCXCCBZffn1JT5PUEiPMM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/wallet/test1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
